add options to script

diff --git a/fake-deshuffle b/fake-deshuffle
--- a/fake-deshuffle
+++ b/fake-deshuffle
@@ -3,50 +3,87 @@
 SCRIPTNAME=$(basename "$0")
 
 fake_deshuffle_one_by_one() {
-  word_len="${#1}"
+  word_len="${#string}"
   for ((j=0; j<$word_len; j++)); do
     for i in {1..5}; do
-      printf "${rnd_list:$(( RANDOM % ${#rnd_list} )):1}"
-      sleep 0.03
+      printf "${rdm_chars:$(( RANDOM % ${#rdm_chars} )):1}"
+      sleep "$speed"
       printf "\033[1D"
     done
-    printf "${1:$j:1}"
+    printf "${string:$j:1}"
   done
 }
 
 fake_deshuffle_all() {
-  word_len="${#1}"
+  word_len="${#string}"
   for ((k=0; k<$word_len; k++)); do
     len_left=$((word_len-k))
     for ((i=0; i<4; i++)); do
       for ((j=0; j<$len_left; j++)); do
-        printf "${ncl}${rnd_list:$(( RANDOM % ${#rnd_list} )):1}"
+        printf "${ncl}${rdm_chars:$(( RANDOM % ${#rdm_chars} )):1}"
       done
-      sleep 0.03
+      sleep "$speed"
       printf "\033[${len_left}D"
     done
-    printf "${1:$k:1}"
+    printf "${string:$k:1}"
   done
 }
 
-# Help
-if [[ "$1" == "--help" || "$1" == "" ]]; then
-  printf "Usage: $SCRIPTNAME [--onebyone] word
---help          Show this message.
---onebyone      Looks like a char by char brute force string cracker.
-(default)       Looks like a realistic brute force string cracker.
+# Default values
+default_speed="0.06"
+default_rdm_chars="АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψω"
 
-Example: $SCRIPTNAME --onebyone ᵛᵉʳᶦᶠᶦᵉᵈ
-"
-  exit
+# Initialize variables
+speed=$default_speed
+rdm_chars=$default_rdm_chars
+one_by_one=false
+
+# Parse arguments
+while getopts ":h1t:c:s:" opt; do
+  case ${opt} in
+    h )
+      echo "Usage: $SCRIPTNAME [-1] [-t value] [-c value] -s value"
+      echo "  -h               Display help"
+      echo "  -1               Set one_by_one flag"
+      echo "  -t value         Set speed value (default: $default_speed)"
+      echo "  -c value         Set random characters to use (default: $default_rdm_chars)"
+      echo "  -s value         Set string value (mandatory)"
+      exit 0
+      ;;
+    1 )
+      one_by_one=true
+      ;;
+    t )
+      speed=$OPTARG
+      ;;
+    c )
+      rdm_chars=$OPTARG
+      ;;
+    s )
+      string=$OPTARG
+      ;;
+    \? )
+      echo "Invalid option: -$OPTARG" 1>&2
+      exit 1
+      ;;
+    : )
+      echo "Invalid option: -$OPTARG requires an argument" 1>&2
+      exit 1
+      ;;
+  esac
+done
+
+# Check if -s is provided
+if [ -z "$string" ]; then
+  echo "Error: -s is a mandatory argument" 1>&2
+  echo "Usage: script.sh [-1] [-t value] [-c value] -s value"
+  exit 1
 fi
 
-rnd_list="ᵡᵉᶜᵅʷ³ᶦᵝ⁾⁸ᶳʲ¹ᵍʲᵟⁿᵠᵘ⁷ᶿʸᵈᵏ⁵ᶠᵐˢ⁶ʳ⁻ᵠᶧⁱʳ⁽ᵖ⁴⁹ᵐᶻᵋᶢᵍᶩᶜᵆ²⁰ᵒˣˡᵞᵛᵄᵇᶹᵗᵗ⁺ʰᵃⁿᶠ"  
-
-if [[ "$1" == "--onebyone" ]]; then
-  fake_deshuffle_one_by_one "$2"
+if $one_by_one; then
+  fake_deshuffle_one_by_one
 else
-  fake_deshuffle_all "$1"
+  fake_deshuffle_all
 fi
 
 printf "\n"
